"""JLCPCB/LCSC component category names for search autocomplete."""

CATEGORIES = [
    "2G/3G/4G/5G Modules",
    "3D Magnetic Sensors",
    "555 Timers / Counters",
    "AC DC Configurable Power Supplies (Factory Assembled)",
    "AC DC Configurable Power Supply Chassis",
    "AC DC Configurable Power Supply Modules",
    "AC DC Converters",
    "AC DC Converters (Off-Board)",
    "AC DC Converters, Offline Switchers",
    "AC DC Desktop, Wall Power Adapters",
    "AC Fans",
    "AC Power Connectors",
    "AC-DC Controllers and Regulators",
    "AC-DC Power Modules",
    "ADCs/DACs - Special Purpose",
    "ARINC",
    "ARINC Inserts",
    "Absorbents, Trays",
    "Accelerometers",
    "Accessories",
    "Accessories - Boots, Seals",
    "Accessories - Caps",
    "Actuators/Cylinders",
    "Adapter Cards",
    "Adapters, Breakout Boards",
    "Adjustable Inductors",
    "Adjustable Power Resistor",
    "Air Conditioner Accessories",
    "Alarms, Buzzers, and Sirens",
    "Alligator, Crocodile, Heavy Duty Clips",
    "Aluminum - Polymer Capacitors",
    "Aluminum Case/Porcelain Tube Resistance",
    "Aluminum Electrolytic Capacitors",
    "Aluminum Electrolytic Capacitors - Leaded",
    "Aluminum Electrolytic Capacitors - SMD",
    "Ambient Light Sensors",
    "Ambient Light, IR, UV Sensors",
    "Ammeters",
    "Amplifiers",
    "Analog Front End (AFE)",
    "Analog Multipliers, Dividers",
    "Analog Switches - Special Purpose",
    "Analog Switches, Multiplexers",
    "Analog Switches, Multiplexers, Demultiplexers",
    "Analog and Digital Output",
    "Analog to Digital Converters (ADC)",
    "Analog to Digital Converters (ADCs) Evaluation Boards",
    "Analyzers",
    "Anemometer",
    "Angle Squares",
    "Angle, Linear Position Measuring",
    "Antenna spring",
    "Antennas",
    "Anti-static Bags",
    "Anti-static Gloves",
    "Anti-static Wristbands",
    "Application Specific Clock/Timing",
    "Application Specific Microcontrollers",
    "Arc Flash Protection",
    "Arms, Mounts, Stands",
    "Arrays, Edge Type, Mezzanine (Board to Board)",
    "Arrays, Signal Transformers",
    "Asbestos Net",
    "Assorted Tool Kits",
    "Attenuators",
    "Audible Alarms",
    "Audio Amplifier Evaluation Boards",
    "Audio Amplifiers",
    "Audio Connectors",
    "Audio Interface ICs",
    "Audio Products Accessories",
    "Audio Special Purpose",
    "Audio Transformers",
    "Automated External Defibrillators",
    "Automatic Transfer Switches",
    "Automobile Connectors",
    "Automotive Fuses",
    "Automotive Relays",
    "Avalanche Diodes",
    "BNC Interface",
    "BV Terminal",
    "Backplane Connector Accessories",
    "Backplane Connector Contacts",
    "Backplane Connector Housings",
    "Backplane Connectors",
    "Backshells and Cable Clamps",
    "Balun",
    "Banana Connectors / Alligator Clips",
    "Banana and Tip Connector Accessories",
    "Banana and Tip Connector Adapters",
    "Banana and Tip Connectors",
    "Banana, Meter Interface",
    "Barrel Audio Cables",
    "Barrel Connector Adapters",
    "Barrel Connectors",
    "Barrel Power Cables",
    "Barrel, Bullet Connectors",
    "Barrier Blocks",
    "Barrier Terminal Blocks",
    "Battery Chargers",
    "Battery Chargers ICs",
    "Battery Holders, Clips, Contacts",
    "Battery Management",
    "Battery Packs",
    "Battery Product Accessories",
    "Battery connector",
    "Between Series Adapters",
    "Binding Posts",
    "Bioculture",
    "Bipolar (BJT)",
    "Bipolar RF Transistors",
    "Bipolar Transistor Arrays",
    "Bipolar Transistor Arrays, Pre-Biased",
    "Blade Type Power Connector Accessories",
    "Blade Type Power Connector Assemblies",
    "Blade Type Power Connector Contacts",
    "Blade Type Power Connector Housings",
    "Blade Type Power Connectors",
    "Bluetooth Modules",
    "Board In, Direct Wire to Board",
    "Board Mount Power Supply Accessorie",
    "Board Spacers, Stackers (Board to Board)",
    "Board Supports",
    "Board-to-Board and Backplane Connector",
    "Bobbins (Coil Formers), Mounts, Hardware",
    "Body Protection",
    "Borescopes",
    "Bridge Rectifiers",
    "Brushed DC Motor Drivers",
    "Brushless DC (BLDC) Motor Driver",
    "Buffers, Drivers, Receivers, Transceivers",
    "Bushings, Grommets",
    "Buzzers",
    "CAN Bus Modules",
    "CAN Controllers",
    "CAN Transceivers",
    "CODECS",
    "CPLDs (Complex Programmable Logic Devices)",
    "Cable Ferrites",
    "Cable Markers",
    "Cable Pull Switches",
    "Cable Supports and Fasteners",
    "Cable Ties - Holders and Mountings",
    "Cable Ties and Zip Ties",
    "Cable and Cord Grips",
    "Cables, Wires",
    "Cables, Wires Accessories",
    "Calibrating",
    "Camera Modules",
    "Camera/Sensors",
    "Cameras",
    "Capacitive Sensor IC",
    "Capacitor Kits",
    "Capacitor Networks, Arrays",
    "Capacitors",
    "Card Edge Connector Accessories",
    "Card Edge Connector Adapters",
    "Card Edge Connector Contacts",
    "Card Edge Connector Housings",
    "Card Edge Connectors",
    "Casters",
    "Centrifuge Tubes and Bottles",
    "Centronics Connectors",
    "Ceramic Capacitors",
    "Ceramic Filters",
    "Ceramic Resonators",
    "Charge Pumps",
    "Charger",
    "Chassis Mount Resistors",
    "Chip Resistor - Surface Mount",
    "Circuit Board Indicators, Arrays, Light Bars, Bar Graphs",
    "Circuit Breakers",
    "Circuit Protection",
    "Circuit Protection Accessories",
    "Circuit breaker accessories",
    "Circular Connector Accessories",
    "Circular Connector Adapters",
    "Circular Connector Assemblies",
    "Circular Connector Contacts",
    "Circular Connector Housings",
    "Circular Connectors",
    "Circular Connectors & Cable Connectors",
    "Circular DIN Connectors",
    "Clamp",
    "Clamp Filters (Ferrite Core with Case)",
    "Clamp Meters",
    "Cleaning Brush",
    "Cleaning, Sterilization, and Wiping Supplies",
    "Clock Buffers, Drivers",
    "Clock Buffers, Drivers, Distributors",
    "Clock Generators, PLLs, Frequency Synthesizers",
    "Clock and Data Recovery / Retiming",
    "Clock/Timing",
    "Closed-End Terminal",
    "Coaxial Connector (RF) Accessories",
    "Coaxial Connector (RF) Adapters",
    "Coaxial Connector (RF) Assemblies",
    "Coaxial Connector (RF) Contacts",
    "Coaxial Connector (RF) Terminators",
    "Coaxial Connectors (RF)",
    "Cold press terminals/Terminal blocks",
    "Cold-pressed Terminals",
    "Color Ring Inductors / Through Hole Inductors",
    "Color Sensors",
    "Color Sensors (on-board)",
    "Color Sensors - Industrial",
    "Common Mode Chokes",
    "Common Mode Filters",
    "Comparators",
    "Compass, Magnetic Field (Modules)",
    "Computer Power Supply Units",
    "Computers",
    "Conductivity Meter",
    "Configurable Switch Bodies",
    "Configurable Switch Components",
    "Configurable Switch Contact Blocks",
    "Configurable Switch Illumination Sources",
    "Configurable Switch Lens",
    "Configuration PROMs for FPGAs",
    "Connecting accessories",
    "Connector Accessories",
    "Connector Adapter Kits",
    "Connector Housings",
    "Connectors, Interconnects",
    "Contactors (Electromechanical)",
    "Contactors (Solid State)",
    "Contacts",
    "Contacts, Spring Loaded (Pogo Pins), and Pressure",
    "Container Brush",
    "Controller Accessories",
    "Copy Paper",
    "Counters",
    "Counters, Dividers",
    "Counters, Hour Meters",
    "Cover Slips and Microscope Slides",
    "Crash Bars",
    "Crucible",
    "Crystal Oscillators",
    "Crystal, Oscillator, Resonator Accessories",
    "Crystals",
    "Crystals, Oscillators, Resonators",
    "Current Regulation - Diodes, Transistors",
    "Current Regulation/Management",
    "Current Sense Amplifiers",
    "Current Sense Resistors",
    "Current Sense Resistors / Shunt Resistors",
    "Current Sense Transformers",
    "Current Sensors",
    "Current Source / Constant Current Source",
    "Current Transformers",
    "Current/Voltage Transducer Monitors",
    "Cushioning Materials",
    "D-Sub / VGA Connectors",
    "D-Sub Connector",
    "D-Sub, D-Shaped Connector Accessories",
    "D-Sub, D-Shaped Connector Adapters",
    "D-Sub, D-Shaped Connector Backshells, Hoods",
    "D-Sub, D-Shaped Connector Contacts",
    "D-Sub, D-Shaped Connector Housings",
    "D-Sub, D-Shaped Connector Jackscrews",
    "D-Sub, D-Shaped Connector Terminators",
    "D-Sub, D-Shaped Connectors",
    "DC AC Inverters",
    "DC Brushless Fans (BLDC)",
    "DC DC Converters",
    "DC DC Converters (Off-Board)",
    "DC DC Switching Controllers",
    "DC Power Connectors",
    "DC Power Supplies",
    "DC-DC Converters",
    "DC-DC Power Modules",
    "DC/DC & AC/DC (Off-Line) SMPS Evaluation Boards",
    "DDR SDRAM",
    "DIACs, SIDACs",
    "DIN 41612",
    "DIP Switches",
    "DIP Switches/SIP Switches",
    "DSP (Digital Signal Processors)",
    "DVI Connectors",
    "Darlington Transistor Arrays",
    "Darlington Transistors",
    "Data Acquisition",
    "Data Acquisition (DAQ)",
    "Data Cable",
    "Delay Lines",
    "Desktop Computers",
    "Desoldering Tools",
    "Detectors & Scanners",
    "Development Boards, Kits, Programmers",
    "Development Boards, Kits, Programmers Accessories",
    "Differential Amplifiers",
    "Differential Pressure Transmitters",
    "Digital Comparators",
    "Digital Isolators",
    "Digital Isolators (with Power)",
    "Digital Potentiometers",
    "Digital Signal Processors (DSP/DSC)",
    "Digital Transistors",
    "Digital Tube Drivers",
    "Digital to Analog Converters (DAC)",
    "Digital to Analog Converters (DACs) Evaluation Boards",
    "Dimensional Measuring",
    "Din Rail, Channel",
    "Diode Arrays",
    "Diodes",
    "Diodes - General Purpose",
    "Diodes - Variable Capacitance",
    "Direct Digital Synthesis (DDS)",
    "Disconnect Switch Components",
    "Discrete Semiconductors",
    "Display Backlights",
    "Display Drivers",
    "Display, Monitor - LCD Driver/Controller",
    "Disposable Masks",
    "Disposable fuses",
    "Distance Measuring",
    "Distance Meters",
    "Distiller",
    "Docking Station",
    "Double-sided Tape",
    "Drills",
    "Drivers, Receivers, Transceivers",
    "Duplexers",
    "E Terminal",
    "EEPROM",
    "EMI/RFI Filters (LC, RC Networks)",
    "ESD and Surge Protection (TVS/ESD)",
    "Edgeboard Connectors",
    "Educational Kits",
    "Electric Actuators/Cylinders",
    "Electric Double Layer Capacitors (EDLC), Supercapacitors",
    "Electric Soldering Iron",
    "Electric Soldering Iron Kit",
    "Electronic Load",
    "Electrostatic Protection",
    "Embedded",
    "Embedded Complex Logic (FPGA, CPLD) Evaluation Boards",
    "Embedded Computer Accessories",
    "Embedded Computer Interface Boards",
    "Embedded Computers",
    "Embedded MCU, DSP Evaluation Boards",
    "Emergency Lighting",
    "Emergency Stop (E-Stop) Switches",
    "Encoders",
    "Encoders - Industrial",
    "Encoders, Decoders, Converters",
    "Energy Metering",
    "Energy Metering Modules",
    "Environmental Testers",
    "Equipment circuit breaker",
    "Ethernet Connectors / Modular Connectors (RJ45 RJ11)",
    "Ethernet Controllers",
    "Ethernet Modules",
    "Ethernet Switches",
    "Ethernet Transceivers",
    "Evaluation Boards",
    "Evaluation and Demonstration Boards and Kits",
    "Exit Signs",
    "Expansion Boards, Daughter Cards",
    "External/Internal Power Supply Accessories",
    "Eye Protection",
    "Eyepieces, Lenses",
    "FET Input Amplifiers",
    "FET, MOSFET Arrays",
    "FETs, MOSFETs",
    "FFC, FPC (Flat Flexible) Connector Accessories",
    "FFC, FPC (Flat Flexible) Connector Assemblies",
    "FFC, FPC (Flat Flexible) Connector Contacts",
    "FFC, FPC (Flat Flexible) Connector Housings",
    "FFC, FPC (Flat Flexible) Connectors",
    "FIFOs Memory",
    "FPGAs (Field Programmable Gate Array)",
    "FPGAs (Field Programmable Gate Array) with Microcontrollers",
    "FRAM",
    "FRD / MPD Terminal",
    "Fall Protection",
    "Fan Accessories",
    "Fan Cords",
    "Fast Recovery / High Efficiency Diodes",
    "Feed Through Capacitors",
    "Female Headers",
    "Ferrite Beads",
    "Ferrite Beads and Chips",
    "Ferrite Cores",
    "Fiber Optic / Laser Sensors",
    "Fiber Optic Attenuators",
    "Fiber Optic Cables",
    "Fiber Optic Cables Management",
    "Fiber Optic Connector Accessories",
    "Fiber Optic Connector Adapters",
    "Fiber Optic Connector Assemblies",
    "Fiber Optic Connector Housings",
    "Fiber Optic Connectors",
    "Fiber Optic Receivers",
    "Fiber Optic Switches, Multiplexers, Demultiplexers",
    "Fiber Optic Transceiver Modules",
    "Fiber Optic Transmitters - Discrete",
    "Fiber Optic Transmitters - Drive Circuitry Integrated",
    "Fiber Optical Transceivers",
    "Files",
    "Film Capacitors",
    "Filter Paper",
    "Filters",
    "Filters - Active",
    "Filters and Membranes",
    "Finger Guards, Filters & Sleeves",
    "Fire Blanket",
    "Fire Protection",
    "First-Aid Supplies",
    "Fittings, Couplings, and Distributors",
    "Fixed Inductors",
    "Flask",
    "Flat Ribbon Cables",
    "Flip Flops",
    "Float Level Senors",
    "Float, Level Sensors",
    "Float, Level Sensors - Industrial",
    "Flood Control",
    "Flow Sensor",
    "Flow Sensors",
    "Flow Sensors - Industrial",
    "Flow Switch",
    "Foil Connectors",
    "Font chips",
    "Foot Protection",
    "Foot switches",
    "Footwear",
    "Force Sensors, Load Cells",
    "Force Sensors, Load Cells - Industrial",
    "Force/Torque Gauges",
    "Free Hanging, Panel Mount",
    "Frequency Meters",
    "Full Half-Bridge (H Bridge) Drivers",
    "Funnel",
    "Fuseholders",
    "Fuses",
    "GNSS Modules",
    "Gadgets, Gizmos",
    "Gas Detectors",
    "Gas Discharge Tube Arresters (GDT)",
    "Gas Sensor",
    "Gate Drive Optocoupler",
    "Gate Drivers",
    "Gates and Inverters",
    "Gates and Inverters - Multi-Function, Configurable",
    "Gateways, Routers",
    "Glass Discharge Tubes",
    "Global Source",
    "Gloss Meter",
    "Gloves",
    "Ground Fault Circuit Interrupter (GFCI)",
    "Grounding Braid, Straps",
    "Gyroscopes",
    "HDMI Connectors",
    "Hall Switches",
    "Hammers",
    "Hand and Arm Protection",
    "Handles",
    "Hard Disk Connector (SAS/SATA/M.2)",
    "Hard Metric, Standard",
    "Hardness Testers",
    "Hardware Accessories",
    "Harnesses",
    "Headers, Male Pins",
    "Headers, Plugs and Sockets",
    "Headers, Receptacles, Female Sockets",
    "Headers, Specialty Pin",
    "Heat Guns, Torches, Accessories",
    "Heat Shrink Fabric",
    "Heat Shrink Wrap",
    "Heat Sinks",
    "Heat sink / cooling fin",
    "Heater Accessories",
    "Heating Core",
    "Heavy Duty Connector Accessories",
    "Heavy Duty Connector Assemblies",
    "Heavy Duty Connector Contacts",
    "Heavy Duty Connector Frames",
    "Heavy Duty Connector Housings, Hoods, Bases",
    "Heavy Duty Connector Inserts, Modules",
    "Heavy Duty Connectors",
    "Helical Filters",
    "High Frequency (RF) Relays",
    "Hoists",
    "Hole Saws",
    "Horn-Type Electrolytic Capacitors",
    "Hot Air Rework Station",
    "Hot Swap Controllers",
    "Housing Contact",
    "Housings (Wire To Board / Wire To Wire)",
    "Housings, Boots",
    "Human Body Sensing Sensor",
    "Humidity, Moisture Sensors",
    "Hybrid Aluminum Electrolytic Capacitors",
    "I/O Expanders",
    "I2C Isolators",
    "IC / Transistor Socket",
    "IC Clips",
    "IC Sockets",
    "IDC Connectors",
    "IGBT Arrays",
    "IGBT Modules",
    "IGBT Transistors / Modules",
    "IGBTs",
    "IMUs (Inertial Measurement Units)",
    "Image Sensors, Camera",
    "Incandescent, Neon Lamps",
    "Inclinometers (ICs)",
    "Inductors (SMD)",
    "Inductors, Coils, Chokes",
    "Industrial - Power Distribution, Surge Protectors",
    "Industrial Automation Accessories",
    "Industrial Automation and Controls",
    "Industrial Camera",
    "Industrial Controllers",
    "Industrial Electric Fan",
    "Industrial Equipment",
    "Industrial Relays",
    "Industrial Sensors",
    "Industrial Sensors Accessories",
    "Industrial Specialized",
    "Industrial Tape",
    "Industrial terminal blocks",
    "Industrial, DIN Rail Power Supplies",
    "Infrared LED Emitters",
    "Infrared Remote Receiver (IRM)",
    "Inline Module Sockets",
    "Inrush Current Limiters (ICL)",
    "Inspecting",
    "Instrumentation Amplifiers",
    "Insulating tape",
    "Integrated Circuits (ICs)",
    "Intelligent Power Modules (IPM)",
    "Interface",
    "Interface - PCIs / PCIEs",
    "Interface - Specialized",
    "Interface Controllers",
    "Interface Modules",
    "Interlock Switches",
    "Inverters",
    "Ion Meter",
    "IrDA Transceiver Modules",
    "Isolated ADCs",
    "Isolated CAN Transceivers",
    "Isolated CAN Transceivers (with Power)",
    "Isolated DC/DC Converters",
    "Isolated I2C (with Power)",
    "Isolated Power Modules",
    "Isolated RS-232 Transceivers (with Power)",
    "Isolated RS-485/422 Transceivers",
    "Isolated RS-485/422 Transceivers with power",
    "Isolated USB ICs",
    "Isolation Amplifiers",
    "Isolation Transformers and Autotransformers, Step Up, Step Down",
    "Isolators",
    "Isolators - Gate Drivers",
    "JFETs",
    "Jacks, Plugs",
    "KVM Switches",
    "Keylock Switches",
    "Keys",
    "Keystone Connector Accessories",
    "Keystone Connectors",
    "Keystone Faceplates, Frames",
    "Keystone Inserts",
    "Knife Connectors",
    "Knives",
    "Knives, Scissors, Shovels, Spoons, Tweezers, and Forceps",
    "LCD Drivers",
    "LCD, OLED Character and Numeric",
    "LCD, OLED, Graphic",
    "LED Addressable, Specialty",
    "LED COBs, Engines, Modules, Strips",
    "LED Character and Numeric",
    "LED Color Lighting",
    "LED Dot Matrix and Cluster",
    "LED Driver Evaluation Boards",
    "LED Drivers",
    "LED Drivers (Off-Board)",
    "LED Drivers ICs",
    "LED Emitters - Infrared, UV, Visible",
    "LED Indication - Discrete",
    "LED Protection",
    "LED Segment Displays",
    "LED Strip Light",
    "LED White Lighting",
    "LED isolation column",
    "LGH Connectors",
    "LIN Transceivers",
    "LVDS ICs",
    "LVDT Transducers (Linear Variable Differential Transformer)",
    "Lab Cleaning Swabs and Brushes",
    "Label Paper",
    "Labels",
    "Labels, Labeling",
    "Laboratory Equipment",
    "Laboratory Labels",
    "Lamps - Magnifying, Task",
    "Laser Diodes, Modules",
    "Laser Drivers",
    "Laser Optics",
    "Laser Optics Accessories",
    "Latches",
    "Leadframe",
    "Leakage Protection ICs",
    "Lenses",
    "Levels",
    "Lifting Equipment",
    "Light Pipes",
    "Lighting Accessories",
    "Lighting Drivers & Controllers",
    "Lighting Protection",
    "Lighting, Ballast Controllers",
    "Limit Switches",
    "Linear",
    "Linear - Analog Multipliers, Dividers",
    "Linear Comparators",
    "Linear Hall Sensors",
    "Linear Voltage Regulator Evaluation Boards",
    "Linear, Compass (ICs)",
    "Liquid, Level",
    "LoRa Modules",
    "Locks & Latches",
    "Logic",
    "Logic Comparators",
    "Logic Gates",
    "Logic Output Optoisolators",
    "Low Noise Amplifiers (LNA) - RF",
    "Lugs",
    "MEMS Microphones",
    "MOSFETs",
    "Magnet Ring, Bead",
    "Magnet Wire",
    "Magnetic Angle Sensors",
    "Magnetic Latching Relays",
    "Magnetic Sensors",
    "Magnetic Wire Connectors",
    "Magnetic, Reed Switches",
    "Magnetics - Transformer, Inductor Components",
    "Magnets",
    "Magnifying Glass",
    "Media Converters",
    "Memory",
    "Memory (ICs)",
    "Memory - Modules",
    "Memory Card, Module Accessories",
    "Memory Cards",
    "Memory Connector (DDR)",
    "Memory Connector Accessories",
    "Memory Connectors",
    "Memory Controllers",
    "Metal Dome Pot",
    "Meters",
    "Mica and PTFE Capacitors",
    "Microcontrollers",
    "Microcontrollers (MCU/MPU/SOC)",
    "Microcontrollers, Microprocessor, FPGA Modules",
    "Micrometer",
    "Microphones",
    "Microplates and PCR Consumables",
    "Microprocessors",
    "Microscopes",
    "Miniature Circuit Breaker",
    "Miniature Residual Current Circuit Breaker",
    "Miniature leakage protection circuit breaker",
    "Mixed Technology",
    "Modems - ICs and Modules",
    "Modular - Flat Cable",
    "Modular Connectors",
    "Modular/Ethernet Connector Accessories",
    "Modular/Ethernet Connector Adapters",
    "Modular/Ethernet Connector Jacks",
    "Modular/Ethernet Connector Jacks With Magnetics",
    "Modular/Ethernet Connector Plug Housings",
    "Modular/Ethernet Connector Plugs",
    "Modular/Ethernet Connector Wiring Blocks",
    "Modules",
    "Molded case circuit breakers",
    "Monitors",
    "Monolithic Crystals",
    "Monostable Multivibrators",
    "Motion Sensors",
    "Motor Driver Boards, Modules",
    "Motor Driver ICs",
    "Motor Drivers, Controllers",
    "Motor Protective Circuit Breaker",
    "Motor Start, Motor Run Capacitors (AC)",
    "Motors - AC, DC",
    "Motors, Actuators, Solenoids and Drivers Accessories",
    "Mouse Pads",
    "Multi Purpose",
    "Multi Purpose Magnets",
    "Multi-Directional Switches",
    "Multi-purpose Brushes",
    "Multidirectional Switch",
    "Multifunction",
    "Multifunction Meters",
    "Multilayer Ceramic Capacitors MLCC - Leaded",
    "Multilayer Ceramic Capacitors MLCC - SMD/SMT",
    "Multimeters",
    "Multiple Conductor Cables",
    "Multivibrators",
    "NAND FLASH",
    "NOR FLASH",
    "NTC Thermistors",
    "Navigation Switches, Joystick",
    "Network Accessories",
    "Networking Solutions Miscellaneous",
    "Niobium Oxide Capacitors",
    "Non-Volatile Memory (ROM)",
    "OLED Display",
    "OR Controllers, Ideal Diodes",
    "ORing Controllers",
    "Office Furniture",
    "Office Machines",
    "Oilstones",
    "Op Amp Evaluation Boards",
    "Operational Amplifier",
    "Optic Spacers, Standoffs",
    "Optical Drives",
    "Optical Inspection Accessories",
    "Optical Instruments",
    "Optical Module Connector",
    "Optical Motion Sensors",
    "Optical Sensors",
    "Optocouplers, Optoisolators",
    "Optoelectronics",
    "Optoelectronics Accessories",
    "Oscillators",
    "Oscilloscope",
    "Outdoor Lighting",
    "PC Card Sockets",
    "PC Pin Receptacles, Socket Connectors",
    "PC Pin, Single Post Connectors",
    "PCB Welding Terminal",
    "PCI / PCIe Connector",
    "PFC (Power Factor Correction)",
    "PFC Controllers",
    "PLDs (Programmable Logic Device)",
    "PTC Resettable Fuses",
    "PTC Thermistors",
    "Packaging Bags",
    "Packing Ropes",
    "Packing Tapes",
    "Pads, Sheets",
    "Panel Meter Accessories",
    "Panel Meters",
    "Panel Mount",
    "Paper and Printing",
    "Parity Generators and Checkers",
    "Particle, Dust Sensors",
    "Particulate Matter (PM) Transmitters",
    "Passives",
    "Patchbay, Jack Panel Accessories",
    "Phase Sequence Indicator",
    "Photo Detectors - CdS Cells",
    "Photo Detectors - Logic Output",
    "Photo Detectors - Remote Receiver",
    "Photodiodes",
    "Photoelectric - Industrial",
    "Photointerrupters - Slot Type - Logic Output",
    "Photointerrupters - Slot Type - Transistor Output",
    "Photonics - Counters, Detectors, SPCM (Single Photon Counting Module)",
    "Photoresistors",
    "Phototransistors",
    "Photovoltaic (Solar Panel) Connector Accessories",
    "Photovoltaic (Solar Panel) Connector Assemblies",
    "Photovoltaic (Solar Panel) Connectors",
    "Pilot & Indicator Lights",
    "Pin Configurable/Selectable Oscillators",
    "Pin Headers",
    "Pin plug",
    "Pins",
    "Pliers",
    "Pluggable Connector Accessories",
    "Pluggable Connector Assemblies",
    "Pluggable Connectors",
    "Pluggable System Terminal Block",
    "Plugs and Receptacles",
    "Polymer Aluminum Capacitors",
    "Polypropylene Film Capacitors (CBB)",
    "Position Sensors",
    "Position, Proximity, Speed (Modules)",
    "Position, Proximity, Speed (Modules) - Industrial",
    "Potentiometers, Variable Resistors",
    "Power Connectors",
    "Power Distribution",
    "Power Distribution Switches",
    "Power Distribution Switches, Load Drivers",
    "Power Distribution, Surge Protectors",
    "Power Driver Modules",
    "Power Entry Connector Accessories",
    "Power Entry Modules (PEM)",
    "Power Factor Meter",
    "Power Inductors",
    "Power Line Filter Modules",
    "Power Management (PMIC)",
    "Power Management - Specialized",
    "Power Meter",
    "Power Module/Power Supply",
    "Power Over Ethernet (PoE) Controllers",
    "Power Relays",
    "Power Suppliers - Board Mount",
    "Power Supplies",
    "Power Supplies - External/Internal (Off-Board)",
    "Power Supply Controllers, Monitors",
    "Power Transformers",
    "Power connector / plug connector",
    "Power over Ethernet (PoE)",
    "Pre-ordered Connectors",
    "Pre-sales",
    "Precision Op Amps",
    "Preparation/Treatment",
    "Pressure Gauges",
    "Pressure Sensors",
    "Pressure Sensors, Transducers",
    "Pressure Sensors, Transducers - Industrial",
    "Pressure Transmitters",
    "Printer",
    "Probe",
    "Process, Temperature",
    "Programmable / Variable Gain Amplifiers (PGA/VGA)",
    "Programmable Logic Device (CPLDs/FPGAs)",
    "Programmable Oscillators",
    "Programmable Timers and Oscillators",
    "Programmable Unijunction Transistors",
    "Programmers, Emulators, and Debuggers",
    "Programming Adapters, Sockets",
    "Protection Relays & Systems",
    "Protective Clothing",
    "Prototyping, Fabrication",
    "Protractors",
    "Proximity Sensors",
    "Proximity Sensors - Industrial",
    "Proximity/Occupancy Sensors Finished Units",
    "Pulling, Support Grips",
    "Pulse Transformers",
    "Pulse Transformers (LAN)",
    "Punches",
    "Pushbutton Switches",
    "Pushbutton Switches - Hall Effect",
    "Quick Connects, Quick Disconnect Connectors",
    "Quick Terminal",
    "RCA Connector",
    "RF Accessories",
    "RF Amplifiers",
    "RF Analyzers",
    "RF Antennas",
    "RF Attenuators",
    "RF Cables",
    "RF Circulators and Isolators",
    "RF Demodulators",
    "RF Detectors",
    "RF Diodes",
    "RF Directional Coupler",
    "RF FETs, MOSFETs",
    "RF Filters",
    "RF Front End (LNA + PA)",
    "RF Front End Circuits",
    "RF Misc ICs and Modules",
    "RF Mixers",
    "RF Modulators",
    "RF Modulators and Demodulators",
    "RF Modules",
    "RF Multiplexers",
    "RF Power Amplifiers",
    "RF Power Controller ICs",
    "RF Power Dividers/Splitters",
    "RF Receiver, Transmitter, and Transceiver Finished Units",
    "RF Receivers",
    "RF Shields",
    "RF Switches",
    "RF Transceiver ICs",
    "RF Transceiver Modules and Modems",
    "RF Transmitters",
    "RF and Wireless",
    "RF, RFID, Wireless Evaluation Boards",
    "RFI and EMI - Contacts, Fingerstock and Gaskets",
    "RFI and EMI - Shielding and Absorbing Materials",
    "RFID Antennas",
    "RFID ICs",
    "RFID Reader Modules",
    "RFID Transponders, Tags",
    "RFID, RF Access, Monitoring ICs",
    "RGB LEDs",
    "RGB LEDs (Built-in IC)",
    "RMS to DC Converters",
    "RS-485 / RS-422 ICs",
    "RS232 Bus Modules",
    "RS232 ICs",
    "RS485 Bus Modules",
    "RTD (Resistance Temperature Detector)",
    "Rags",
    "Random Access Memory (RAM)",
    "Real Time Clocks",
    "Rectangular Connector Accessories",
    "Rectangular Connector Adapters",
    "Rectangular Connector Contacts",
    "Rectangular Connector Housings",
    "Rectangular Connectors",
    "Reed Relays",
    "Reed Switches",
    "Reflective - Analog Output",
    "Reflective - Logic Output",
    "Reflective Optical Interrupters",
    "Reflectors",
    "Refractometer",
    "Relay / Coil Drivers",
    "Relay Modules",
    "Relay Output Monitors",
    "Relay Sockets",
    "Relay Sockets and Accessories",
    "Relay Switches",
    "Relays",
    "Relays Accessories",
    "Rescue Supplies",
    "Resettable Fuses",
    "Residual Current Circuit Breaker",
    "Resistance Testers",
    "Resistor Kits",
    "Resistor Networks, Arrays",
    "Resistors",
    "Resistors Accessories",
    "Resonators",
    "Respiratory",
    "Ring Connectors",
    "Ring Terminal",
    "Robotics Kits",
    "Rocker Switches",
    "Rotary Encoders",
    "Rotary Potentiometers, Rheostats",
    "Rotary Switches",
    "Roughness Tester",
    "SAW Filters",
    "SAW Resonators",
    "SCRs",
    "SCRs - Modules",
    "SD Card / Memory Card Connector",
    "SDRAM",
    "SIM Card Connectors",
    "SMD Quick Terminal",
    "SPI Isolators",
    "SRAM",
    "Safety Capacitors",
    "Safety Compliance Testers",
    "Safety Goggles",
    "Safety Light Curtains",
    "Safety Relays",
    "Safety Ropes",
    "Safety Signs",
    "Safety circuit breaker",
    "Sample / Hold Amplifiers",
    "Sample Container",
    "Sandpaper",
    "Saws",
    "Scale Dials",
    "Schottky Diodes",
    "Scissors",
    "Screw Connectors",
    "Screw Terminal Blocks",
    "Sealing Film",
    "Security Verification / Encryption ICs",
    "Selector Switches",
    "Semiconductor Discharge Tubes (TSS)",
    "Sensor Cable Accessories",
    "Sensor Evaluation Boards",
    "Sensor Interface Junction Blocks",
    "Sensor Matched Magnets",
    "Sensor Modules",
    "Sensor and Detector Interfaces",
    "Sensor, Capacitive Touch",
    "Sensor, Transducer Accessories",
    "Sensor, Transducer Amplifiers",
    "Serial Device Servers",
    "Serializers, Deserializers",
    "Shielding clip",
    "Shift Registers",
    "Shock Sensors",
    "Shunts, Jumpers",
    "SiC Diodes",
    "Signal Buffers, Repeaters, Splitters",
    "Signal Conditioners and Isolators",
    "Signal Generator",
    "Signal Relays",
    "Signal Switches, Multiplexers, Decoders",
    "Signal Terminators",
    "Silicon Capacitors",
    "Silicon Carbide Field Effect Transistor (MOSFET)",
    "Single Bipolar Transistors",
    "Single Diodes",
    "Single FETs, MOSFETs",
    "Single IGBTs",
    "Single Zener Diodes",
    "Single, Pre-Biased Bipolar Transistors",
    "Slide Potentiometers",
    "Slide Switches",
    "Slings",
    "Small Parts Organizers",
    "Socket Accessories",
    "Socket Adapters",
    "Sockets",
    "Sockets for ICs, Transistors",
    "Solar Cells",
    "Solder Feeder",
    "Solder Lug Connectors",
    "Solder Pot",
    "Solder Sleeve",
    "Solder Wire / Solder Line",
    "Soldering Iron Stand",
    "Soldering Station",
    "Soldering Tip",
    "Solid State Drives (SSDs), Hard Disk Drives (HDDs)",
    "Solid State Lighting Connector Accessories",
    "Solid State Lighting Connector Assemblies",
    "Solid State Lighting Connector Contacts",
    "Solid State Lighting Connectors",
    "Solid State Relays (MOS Output)",
    "Solid State Relays (SSR)",
    "Solid State Relays (Triac Output)",
    "Sorbents",
    "Spade Connectors",
    "Spade Terminal",
    "Spades,Chisels",
    "Speakers",
    "Special Consumables",
    "Special Purpose Amplifiers",
    "Special Purpose Isolators",
    "Special Purpose Regulators",
    "Special Purpose Transistors",
    "Specialized",
    "Specialized Connectors",
    "Specialized Connectors Terminals",
    "Specialized ICs",
    "Specialized Memory - Modules, Cards",
    "Specialized Resistors",
    "Specialized Sensors",
    "Specialized Terminal Blocks",
    "Specialized Tools",
    "Specialty Equipment",
    "Specialty Logic",
    "Specialty Transformers",
    "Spiral Wrap, Expandable Sleeving",
    "Spring Clamp System Terminal Block",
    "Spring Loaded",
    "Stand Alone Programmers",
    "Stepper Motor Driver",
    "Stirring Bar",
    "Storage Products",
    "Strain Gauges",
    "Subscriber Identification Module (SIM) Cards",
    "Super Barrier Rectifiers (SBR)",
    "Supervisor and Reset ICs",
    "Supervisors",
    "Surge Protection Devices (SPDs)",
    "Surge Suppression ICs",
    "Switch Accessories / Caps",
    "Switches (Solid State)",
    "Switches, Hubs",
    "Switching Converter, SMPS Transformers",
    "Switching Diodes",
    "Synchronous Rectifier Controllers",
    "System On Chip (SoC)",
    "T-shirts",
    "TRIACs",
    "TVS Diodes",
    "Tachometer / RPM Meter",
    "Tactile Switches",
    "Tantalum - Polymer Capacitors",
    "Tantalum Capacitors",
    "Telecom",
    "Telecom Interface ICs",
    "Temperature Compensated Crystal Oscillators (TCXO)",
    "Temperature Sensors",
    "Temperature Sensors - Analog and Digital Output - Industrial",
    "Temperature and Humidity Meter",
    "Temperature and Humidity Sensor",
    "Terminal Accessories",
    "Terminal Adapters",
    "Terminal Block Accessories",
    "Terminal Block Adapters",
    "Terminal Block Contacts",
    "Terminal Block Jumpers",
    "Terminal Block Marker Strips",
    "Terminal Block Wire Ferrules",
    "Terminal Blocks",
    "Terminal Junction Systems",
    "Terminal Strips and Turret Boards",
    "Terminals",
    "Test Pen",
    "Test Points",
    "Test Points / Test Rings",
    "Test Weights",
    "Test and Measurement Accessories",
    "Testing Supplies",
    "Thermal Cutoffs (Thermal Fuses)",
    "Thermal Imager",
    "Thermal Management",
    "Thermal Pad",
    "Thermo-meters",
    "Thermocouples, Temperature Probes",
    "Thermostat Switches",
    "Thermostats - Mechanical",
    "Thermostats - Mechanical - Industrial",
    "Thermostats - Solid State",
    "Thin Film Capacitors",
    "Through Hole Ceramic Capacitors",
    "Through Hole Resistors",
    "Thumbwheel Potentiometers",
    "Thumbwheel Switches",
    "Thyristors",
    "Thyristors (SCR)/Modules",
    "Thyristors (TSS)",
    "Tilt Switches",
    "Time Delay Relays",
    "Time Delays",
    "Timers / Counters",
    "Toggle Switches",
    "Tool Accessories",
    "Touch Screen Controllers",
    "Touch Sensors",
    "Transformer Drivers",
    "Transient Voltage Suppressors (TVS)",
    "Transistor, Photovoltaic Output Optoisolators",
    "Translators, Level Shifters",
    "Transparent Tape",
    "Triac, SCR Output Optoisolators",
    "Trigger Diodes",
    "Trimmer Potentiometers",
    "Trimmers, Variable Capacitors",
    "Trucks",
    "Turret Connectors",
    "Tweezers",
    "UART",
    "UARTs (Universal Asynchronous Receiver Transmitter)",
    "USB Connectors",
    "USB Conversion Modules",
    "USB Converters",
    "USB Flash Drives",
    "USB HUB Controllers",
    "USB PD",
    "USB cable/data cable",
    "USB, DVI, HDMI Connector Accessories",
    "USB, DVI, HDMI Connector Adapters",
    "USB, DVI, HDMI Connector Assemblies",
    "USB, DVI, HDMI Connectors",
    "Ultrasonic Receivers, Transmitters",
    "Ultrasonic Receivers, Transmitters - Industrial",
    "Uncategorized",
    "Uninterruptible Power Supply (UPS) Systems",
    "Universal Bus Functions",
    "V-A Meter",
    "V/F and F/V Converters",
    "VCOs (Voltage Controlled Oscillators)",
    "Vacuum Fluorescent (VFD)",
    "Value Display Potentiometers",
    "Variable Capacitance (Varicaps, Varactors)",
    "Varistors",
    "Varistors, MOVs",
    "Vibration Sensors",
    "Video Amplifiers",
    "Video Interface ICs",
    "Video Processing",
    "Voice Record and Playback",
    "Voltage Controlled Oscillators (VCOs)",
    "Voltage Reference",
    "Voltage Regulators - DC DC Switching Regulators",
    "Voltage Regulators - Linear + Switching",
    "Voltage Regulators - Linear Regulator Controllers",
    "Voltage Regulators - Linear, Low Drop Out (LDO) Regulators",
    "Voltmeters",
    "Weights",
    "WiFi Modules",
    "Wire Pin Connectors",
    "Wire Pin Terminal",
    "Wire Splice Connectors",
    "Wire To Board Connector",
    "Wire Wrap",
    "Wire to Board",
    "Wire to Board Connectors",
    "Wireless Charge-Discharge ICs",
    "Wireless Charging Coils",
    "XLR (Cannon) Connectors",
    "Xenon Lighting",
    "Zener Diode Arrays",
    "Zener Diodes",
    "ZigBee Modules",
    "relay",
    "terminal  accessories",
]
